# ===========================
#  色彩定義 (全域共用)
# ===========================
COLOR_BG_MAIN = "#2E2E2E"
COLOR_BG_SUB = "#3C3C3C"
COLOR_BG_PANEL = "#454545"
COLOR_TEXT = "#E0E0E0"
COLOR_ACCENT_GREEN = "#4CAF50"
COLOR_ACCENT_YELLOW = "#FFC107"
COLOR_ACCENT_BLUE = "#2196F3"
COLOR_ACCENT_RED = "#F44336"
COLOR_ACCENT_GREY = "#9E9E9E"
COLOR_BTN_BG = "#5C5C5C"
COLOR_BTN_FG = "#FFFFFF"
COLOR_LOG_BG = "#1E1E1E"
COLOR_LOG_FG = "#00FF00"
COLOR_BORDER="#cccccc"